[package]
name = "libwebauthn"
description = "FIDO2 (WebAuthn) and FIDO U2F platform library for Linux written in Rust "
version = "0.1.2"
authors = ["Alfie Fresta <alfie.fresta@gmail.com>"]
edition = "2021"
license-file = "../COPYING"
homepage = "https://github.com/linux-credentials"
repository = "https://github.com/linux-credentials/libwebauthn"

[lib]
name = "libwebauthn"
path = "src/lib.rs"

[features]
default = []
hid-device-tests = ["virtual-hid-device"]
virtual-hid-device = ["solo"]
nfc = ["apdu-core", "apdu", "thiserror"]
pcsc = [ "nfc", "dep:pcsc" ]

[dependencies]
base64-url = "2.0.0"
dbus = "0.9.5"
tracing = "0.1.29"
tracing-futures = { version = "0.2.5", features = ["tokio-executor"] }
maplit = "1.0.2"
sha2 = "0.10.2"
uuid = { version = "1.5.0", features = ["serde", "v4"] }
async-trait = "0.1.36"
futures = "0.3.5"
tokio = { version = "1.1.1", features = ["full"] }
serde = "1.0.110"
serde_cbor = "0.11.1"
serde-indexed = "0.1.1"
serde_derive = "1.0.123"
serde_repr = "0.1.6"
serde_bytes = "0.11.5"
num-traits = "0.2"
num-derive = "0.4.1"
byteorder = "1.3.4"
num_enum = "0.7.1"
x509-parser = "0.16.0"
time = "0.3.35"
curve25519-dalek = "4.1.3"
hex = "0.4.3"
mockall = "0.11.4"
hidapi = { version = "2.4.1", default-features = false, features = [
    "linux-static-hidraw",
] }
bitflags = "2.4.1"
rand = "0.8.4"
p256 = { version = "0.13.2", features = ["ecdh", "arithmetic", "serde"] }
heapless = "0.7"
cosey = "0.3.2"
aes = "0.8.2"
hmac = "0.12.1"
cbc = { version = "0.1", features = ["alloc"] }
hkdf = "0.12"
solo = { path = "../solo", optional = true }
text_io = "0.1"
tungstenite = { version = "0.20.1" }
tokio-tungstenite = { version = "0.20.1", features = [
    "rustls-tls-native-roots",
] }
tokio-stream = "0.1.4"
snow = { version = "0.10.0-alpha.1", features = ["use-p256"] }
ctap-types = { version = "0.3.2" }
btleplug = "0.11.7"
apdu-core = { version = "0.4.0", optional = true }
apdu = { version = "0.4.0", optional = true }
thiserror = { version = "2.0.12", optional = true }
pcsc = { version = "2.9.0", optional = true }


[dev-dependencies]
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
qrcode = "0.12"
